// news-homepage/src/components/Card.tsx
import { CardI } from "../interface/interfaces"
import { motion } from 'framer-motion'
import { LazyLoadImage } from 'react-lazy-load-image-component'
import { fadeIn } from '../utils/motions'
const Card = ({ card, index }: CardI) => {
    const { body, img, title } = card
    return (
        <motion.div variants={fadeIn(index * .2, 1, 'left')} 
        className="flex-grow flex gap-1 lg:gap-0 items-stretch">
            <LazyLoadImage effect="blur" className="flex-grow md:w-[200px] md:h-[160px] h-[150px]" src={img} alt={title} />
            <div className="lg:ml-3">
                <span className="text-2xl xl:text-4xl text-grayish-blue">{'0' + index}</span>
                <h4 className="text-xl xl:text-2xl my-2 cursor-pointer hover:text-soft-orange duration-300 transition-all">{title}</h4>
                <p className="text-sm md:text-base xl:text-xl">{body}</p>
            </div>
        </motion.div>
    )
}

export default Card

// fly-dark/src/components/Card.vue
<script setup>
const Prop = defineProps({
  card: {
    type: Object,
    default: null,
  },
  index: {
    type: Number,
    default: 0,
  },
});
import { itemAnimate } from "../utils/motions";
</script>
<template>
  <div
    v-motion="itemAnimate(index, 'left')"
    class="w-full lg:w-[30%] bg-testimonial p-5 rounded text-white mb-2"
  >
    <p class="lg:text-base text-sm">
      {{ card.title }}
    </p>
    <div class="flex mt-5 gap-2 items-center">
      <img
        class="w-8 h-8 rounded-full"
        :src="card.profile.image"
        :alt="card.profile.name"
      />
      <div class="">
        <h3>{{ card.profile.name }}</h3>
        <p class="text-[10px] lg:text-xs">{{ card.profile.occupation }}</p>
      </div>
    </div>
  </div>
</template>
